dist: xenial

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgtest-dev
      - gcc-7
      - g++-7
      - cmake

before_script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
